version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
  scraper:
    build: ./scraper
  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: